version: '3'

services:

  php:
    build: ./devops/php
    restart: always
    container_name: boilerplate-php
    ports:
      - "${PHP_EXPOSE_PORT:-9090}:9000"
    volumes:
      - ./project:/var/www/html
      - ./devops/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - boilerplate-network

  web:
    build: ./devops/nginx/
    restart: always
    container_name: boilerplate-web
    ports:
      - "${WEB_EXPOSE_PORT:-8080}:80"
    networks:
      - boilerplate-network
    volumes:
      - ./project:/var/www/html
      - ./devops/nginx/boilerplate.conf:/etc/nginx/conf.d/default.conf
      - ./devops/nginx/default.conf:/etc/nginx/nginx.conf
    links:
      - php

networks:
  boilerplate-network:
    driver: bridge