nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                apiKey:
                    type: apiKey
                    description: Your Token
                    name: X-AUTH-TOKEN
                    in: header
        security:
            - apiKey: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc